### ISSUE TITLE
How to connect tacotron2 with LPCNet in inference?

### ISSUE THREAD

**Issue by xiaoyangnihao** [MlWoo/LPCNet#15]
@MlWoo In my opinion, the tacotron2 will predict 18dims bfcc and 2dims pitch info, but the lpcnet seems need 55dims features in mozilla/LPCNet, so how to inference ?

**Comment by MlWoo** [comment]
@xiaoyangnihao please read the readme on `cmake` branch. https://github.com/MlWoo/LPCNet/blob/cmake/test_lpcnet.py#L112 may help you.

**Comment by xiaoyangnihao** [comment]
> @xiaoyangnihao please read the readme on `cmake` branch. https://github.com/MlWoo/LPCNet/blob/cmake/test_lpcnet.py#L112 may help you.

Thanks, I will try.

**Comment by xiaoyangnihao** [comment]
@MlWoo I download the cmake branch. But when I excute cmake .. and make -j4. Some errors come out like this.
![image](https://user-images.githubusercontent.com/14233490/105135514-1f31a280-5b2b-11eb-8343-8eae0a84cd89.png)
It seems no errors in code. Can you give some advices? thanks

**Comment by xiaoyangnihao** [comment]
There is a bug in cmake branch,  no 'mdense.py' scipt file in main dir. @MlWoo
