### ISSUE TITLE
if we use tacatron2 , do i need to retrain lpcnet or old pretrained model can be used also.

### ISSUE THREAD

**Issue by alokprasad** [MlWoo/LPCNet#2]
Can i use pretrained model from https://jmvalin.ca/misc_stuff/lpcnet_models, even if i use tacatron2.
and only train tacatron2 as described in readme.

**Comment by alokprasad** [comment]
Can i use pretrained model from  https://jmvalin.ca/misc_stuff/lpcnet_models, even if i use tacatron2

**Comment by MlWoo** [comment]
duplicated with #3 . close it.
